# Generated by Django 6.0.6 on 2026-06-09 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('keyworkds', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
