# Generated by Django 6.0.6 on 2026-06-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keyworkds',
            new_name='keywords',
        ),
    ]
